/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TiketRouteImport } from './routes/tiket'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAgentRouteImport } from './routes/admin/agent'
import { Route as AdminCrewRouteImport } from './routes/admin/crew'
import { Route as AdminPembayaranRouteImport } from './routes/admin/pembayaran'
import { Route as AdminPenggunaRouteImport } from './routes/admin/pengguna'
import { Route as AdminTiketRouteImport } from './routes/admin/tiket'
import { Route as AdminTransaksiRouteImport } from './routes/admin/transaksi'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as TiketCodeRouteImport } from './routes/tiket.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMidtransNotificationRouteImport } from './routes/api/midtrans.notification'
import { Route as OrderOrderIdKonfirmasiRouteImport } from './routes/order.$orderId.konfirmasi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TiketRoute = TiketRouteImport.update({
  id: '/tiket',
  path: '/tiket',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAgentRoute = AdminAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCrewRoute = AdminCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPembayaranRoute = AdminPembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPenggunaRoute = AdminPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTiketRoute = AdminTiketRouteImport.update({
  id: '/tiket',
  path: '/tiket',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTransaksiRoute = AdminTransaksiRouteImport.update({
  id: '/transaksi',
  path: '/transaksi',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const TiketCodeRoute = TiketCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => TiketRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMidtransNotificationRoute = ApiMidtransNotificationRouteImport.update({
  id: '/api/midtrans/notification',
  path: '/api/midtrans/notification',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdKonfirmasiRoute = OrderOrderIdKonfirmasiRouteImport.update({
  id: '/konfirmasi',
  path: '/konfirmasi',
  getParentRoute: () => OrderOrderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/tiket': typeof TiketRouteWithChildren
  '/admin/agent': typeof AdminAgentRoute
  '/admin/crew': typeof AdminCrewRoute
  '/admin/pembayaran': typeof AdminPembayaranRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/tiket': typeof AdminTiketRoute
  '/admin/transaksi': typeof AdminTransaksiRoute
  '/order/$orderId': typeof OrderOrderIdRouteWithChildren
  '/tiket/$code': typeof TiketCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/midtrans/notification': typeof ApiMidtransNotificationRoute
  '/order/$orderId/konfirmasi': typeof OrderOrderIdKonfirmasiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/tiket': typeof TiketRouteWithChildren
  '/admin/agent': typeof AdminAgentRoute
  '/admin/crew': typeof AdminCrewRoute
  '/admin/pembayaran': typeof AdminPembayaranRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/tiket': typeof AdminTiketRoute
  '/admin/transaksi': typeof AdminTransaksiRoute
  '/order/$orderId': typeof OrderOrderIdRouteWithChildren
  '/tiket/$code': typeof TiketCodeRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/midtrans/notification': typeof ApiMidtransNotificationRoute
  '/order/$orderId/konfirmasi': typeof OrderOrderIdKonfirmasiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/tiket': typeof TiketRouteWithChildren
  '/admin/agent': typeof AdminAgentRoute
  '/admin/crew': typeof AdminCrewRoute
  '/admin/pembayaran': typeof AdminPembayaranRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/tiket': typeof AdminTiketRoute
  '/admin/transaksi': typeof AdminTransaksiRoute
  '/order/$orderId': typeof OrderOrderIdRouteWithChildren
  '/tiket/$code': typeof TiketCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/midtrans/notification': typeof ApiMidtransNotificationRoute
  '/order/$orderId/konfirmasi': typeof OrderOrderIdKonfirmasiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/tiket'
    | '/admin/agent'
    | '/admin/crew'
    | '/admin/pembayaran'
    | '/admin/pengguna'
    | '/admin/tiket'
    | '/admin/transaksi'
    | '/order/$orderId'
    | '/tiket/$code'
    | '/admin/'
    | '/api/auth/$'
    | '/api/midtrans/notification'
    | '/order/$orderId/konfirmasi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/tiket'
    | '/admin/agent'
    | '/admin/crew'
    | '/admin/pembayaran'
    | '/admin/pengguna'
    | '/admin/tiket'
    | '/admin/transaksi'
    | '/order/$orderId'
    | '/tiket/$code'
    | '/admin'
    | '/api/auth/$'
    | '/api/midtrans/notification'
    | '/order/$orderId/konfirmasi'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/tiket'
    | '/admin/agent'
    | '/admin/crew'
    | '/admin/pembayaran'
    | '/admin/pengguna'
    | '/admin/tiket'
    | '/admin/transaksi'
    | '/order/$orderId'
    | '/tiket/$code'
    | '/admin/'
    | '/api/auth/$'
    | '/api/midtrans/notification'
    | '/order/$orderId/konfirmasi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  TiketRoute: typeof TiketRouteWithChildren
  OrderOrderIdRoute: typeof OrderOrderIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMidtransNotificationRoute: typeof ApiMidtransNotificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiket': {
      id: '/tiket'
      path: '/tiket'
      fullPath: '/tiket'
      preLoaderRoute: typeof TiketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/agent': {
      id: '/admin/agent'
      path: '/agent'
      fullPath: '/admin/agent'
      preLoaderRoute: typeof AdminAgentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/crew': {
      id: '/admin/crew'
      path: '/crew'
      fullPath: '/admin/crew'
      preLoaderRoute: typeof AdminCrewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pembayaran': {
      id: '/admin/pembayaran'
      path: '/pembayaran'
      fullPath: '/admin/pembayaran'
      preLoaderRoute: typeof AdminPembayaranRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pengguna': {
      id: '/admin/pengguna'
      path: '/pengguna'
      fullPath: '/admin/pengguna'
      preLoaderRoute: typeof AdminPenggunaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tiket': {
      id: '/admin/tiket'
      path: '/tiket'
      fullPath: '/admin/tiket'
      preLoaderRoute: typeof AdminTiketRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/transaksi': {
      id: '/admin/transaksi'
      path: '/transaksi'
      fullPath: '/admin/transaksi'
      preLoaderRoute: typeof AdminTransaksiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiket/$code': {
      id: '/tiket/$code'
      path: '/$code'
      fullPath: '/tiket/$code'
      preLoaderRoute: typeof TiketCodeRouteImport
      parentRoute: typeof TiketRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/midtrans/notification': {
      id: '/api/midtrans/notification'
      path: '/api/midtrans/notification'
      fullPath: '/api/midtrans/notification'
      preLoaderRoute: typeof ApiMidtransNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId/konfirmasi': {
      id: '/order/$orderId/konfirmasi'
      path: '/konfirmasi'
      fullPath: '/order/$orderId/konfirmasi'
      preLoaderRoute: typeof OrderOrderIdKonfirmasiRouteImport
      parentRoute: typeof OrderOrderIdRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAgentRoute: typeof AdminAgentRoute
  AdminCrewRoute: typeof AdminCrewRoute
  AdminPembayaranRoute: typeof AdminPembayaranRoute
  AdminPenggunaRoute: typeof AdminPenggunaRoute
  AdminTiketRoute: typeof AdminTiketRoute
  AdminTransaksiRoute: typeof AdminTransaksiRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAgentRoute: AdminAgentRoute,
  AdminCrewRoute: AdminCrewRoute,
  AdminPembayaranRoute: AdminPembayaranRoute,
  AdminPenggunaRoute: AdminPenggunaRoute,
  AdminTiketRoute: AdminTiketRoute,
  AdminTransaksiRoute: AdminTransaksiRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface TiketRouteChildren {
  TiketCodeRoute: typeof TiketCodeRoute
}

const TiketRouteChildren: TiketRouteChildren = {
  TiketCodeRoute: TiketCodeRoute,
}

const TiketRouteWithChildren = TiketRoute._addFileChildren(TiketRouteChildren)

interface OrderOrderIdRouteChildren {
  OrderOrderIdKonfirmasiRoute: typeof OrderOrderIdKonfirmasiRoute
}

const OrderOrderIdRouteChildren: OrderOrderIdRouteChildren = {
  OrderOrderIdKonfirmasiRoute: OrderOrderIdKonfirmasiRoute,
}

const OrderOrderIdRouteWithChildren = OrderOrderIdRoute._addFileChildren(
  OrderOrderIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  TiketRoute: TiketRouteWithChildren,
  OrderOrderIdRoute: OrderOrderIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMidtransNotificationRoute: ApiMidtransNotificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
